# Generated by Django 4.2.2 on 2023-06-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('C', 'Castrado'), ('M', 'Masculino'), ('F', 'Feminino')], default='C', max_length=1),
        ),
    ]
